CI: don't run `brew update` on macOS
Right now it fails because:

* libnghttp2 and openssl is installed by default
* enchant depends on openssl, so openssl is upgraded
* openssl is upgraded, so libnghttp2 is upgraded
...
and it fails with:

```
 Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/nghttp2/nghttp2.h
Target /usr/local/include/nghttp2/nghttp2.h
is a symlink belonging to nghttp2. You can unlink it:
  brew unlink nghttp2

To force the link and overwrite all conflicting files:
  brew link --overwrite libnghttp2
```

https://github.com/pyenchant/pyenchant/runs/3805580989

Workaround:
Don't run `brew update` - we may get an old version of Enchant,
but let's hope the virtual environment gets updated once in a while ...